[package]
name = "rsleigh"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "pcode-ir",
    "test-harness",
    "rsleigh-generate",
    "generated/x86-shared",
    "generated/x86-subtables",
    "generated/x86-instr-00",
    "generated/x86-instr-01",
    "generated/x86-instr-02",
    "generated/x86-instr-03",
    "generated/x86-instr-04",
    "generated/x86-instr-05",
    "generated/x86-instr-06",
    "generated/x86-instr-07",
    "generated/x86-root",
    "generated/aarch64-shared",
    "generated/aarch64-subtables",
    "generated/aarch64-instr-00",
    "generated/aarch64-instr-01",
    "generated/aarch64-instr-02",
    "generated/aarch64-instr-03",
    "generated/aarch64-root",
    "generated/riscv-shared",
    "generated/riscv-subtables",
    "generated/riscv-instr-00",
    "generated/riscv-instr-01",
    "generated/riscv-root",
]
resolver = "2"

[dependencies]
nom = "7"
thiserror = "1"
tracing = "0.1.40"
quote = "1"
bitvec = "1"
proc-macro2 = "1"
indexmap = "1.9"
ethnum = "1"

[features]
thread = []
no_overflow_inline = []
